networks:
  caddy_net:
    external: true   # reuse your existing caddy_net if you already created it
    # if not created yet, run: docker network create caddy_net

services:
  streamlit:
    build: .  # path to your Streamlit app Dockerfile
    container_name: loyalt-streamlit
    restart: always
    networks:
      - caddy_net
    expose:
      - "8501"   # expose to the network (not host)
    volumes:
      # - ./loyalty-streamlit:/app   # optional: mount code for dev
      - ./data:/app/data           # persist SQLite DB

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_certs:/data
      # - /home/ubuntu/.caddy:/root/.caddy
    environment:
        - ACME_EMAIL=${ACME_EMAIL}
        - GHOST_DOMAIN=${GHOST_DOMAIN}
        - GHOST_PROXY=${GHOST_PROXY}
        - LOYALT_DOMAIN=${LOYALT_DOMAIN}
        - LOYALT_PORT=${LOYALT_PORT}
    networks:
      - caddy_net
